/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspbo;


import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class POSFrame extends javax.swing.JFrame {

    ArrayList<Item> itemlist;
    transaksi trans = new transaksi();
    
    TransaksiBarang transaksibarang = new TransaksiBarang();
    
    DefaultTableModel daftarModel;
    
    int id_transaksi;
    
    boolean paymentStatus;
    
    StatusPembayaran paymentStatusData = new StatusPembayaran();
    
    //TableModel daftarModel;

    int JumlahBelanja = 0;
    /**
     * Creates new form POSFrame
     */
    
    
    public POSFrame() {
        
        DBConnector.initDBConnection();
        
        Item.loadItemFromDB();
        System.out.println(Item.daftarItem.size());
        
        itemlist = Item.daftarItem;
        System.out.println(itemlist.size());
        
        
        initComponents();
        
        
        
        daftarModel = (DefaultTableModel) daftarTable.getModel();
        daftarModel.addTableModelListener(new TableModelListener()
                {
                    @Override
                    public void tableChanged(TableModelEvent tme) {
                        
                        if (tme.getColumn() == 4) {
                          int baris = tme.getFirstRow();
                          
                          float harga = (float)daftarModel.getValueAt(baris, 3);
                          int jumlah = 0;
                          
                          try{
                                jumlah = Integer.parseInt(daftarModel.getValueAt(baris, 4).toString());
                                transaksibarang.daftarJumlahBarang.set(baris,jumlah);

                            } 
                            catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(null, "Please Input a Number!!", "Error", JOptionPane.ERROR_MESSAGE);
                                daftarModel.setValueAt(1, baris, tme.getColumn());
                                 
                            }
                          
                          float total = harga * jumlah;
                          daftarModel.setValueAt(total, baris, 5);
                          System.out.println("harga sebelumnya = "+harga);
                          System.out.println("harga setelahnya = "+total);
                          
                          transaksibarang.daftarHargaBarang.set(baris,total);
                          
                            float totalBelanja = 0.0f;
                            total = 0.0f;
                            for (int i = 0; i < JumlahBelanja; i++) 
                            {
                                total =(float)daftarModel.getValueAt(i, 5);
                                totalBelanja = totalBelanja + total;
                            }
                            
                            int totalBelanjaInt = (int)totalBelanja;
                            totalBelanjaTextField.setText(String.format("%,d",totalBelanjaInt));
                        }
                    }
                    
                }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CodeTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        totalBelanjaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cashTextField = new javax.swing.JTextField();
        PulsaButton = new javax.swing.JButton();
        balekTextfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ListrikButton = new javax.swing.JButton();
        InputButton = new javax.swing.JButton();
        BayarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));

        jPanel1.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setText("Code");

        jLabel2.setText("Name");

        jLabel3.setText("Harga");

        CodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeTextFieldActionPerformed(evt);
            }
        });

        NameTextField.setEditable(false);
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        PriceTextField.setEditable(false);
        PriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextFieldActionPerformed(evt);
            }
        });

        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Code", "Name", "Price Value", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(daftarTable);
        if (daftarTable.getColumnModel().getColumnCount() > 0) {
            daftarTable.getColumnModel().getColumn(0).setResizable(false);
            daftarTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            daftarTable.getColumnModel().getColumn(1).setResizable(false);
            daftarTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(2).setResizable(false);
            daftarTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            daftarTable.getColumnModel().getColumn(3).setResizable(false);
            daftarTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(4).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            daftarTable.getColumnModel().getColumn(5).setResizable(false);
            daftarTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        totalBelanjaTextField.setEditable(false);
        totalBelanjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBelanjaTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Total");

        jLabel8.setText("Cash");

        cashTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashTextFieldActionPerformed(evt);
            }
        });
        cashTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashTextFieldKeyTyped(evt);
            }
        });

        PulsaButton.setText("Pulsa");
        PulsaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulsaButtonActionPerformed(evt);
            }
        });

        balekTextfield.setEditable(false);
        balekTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balekTextfieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Change");

        ListrikButton.setText("Listrik");
        ListrikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListrikButtonActionPerformed(evt);
            }
        });

        InputButton.setText("Input");
        InputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputButtonActionPerformed(evt);
            }
        });

        BayarButton.setText("Bayar");
        BayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PulsaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(InputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListrikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balekTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(cashTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PulsaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ListrikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(BayarButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(balekTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InputButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeTextFieldActionPerformed
        paymentStatus = paymentStatusData.getPaymentStatus();
        
        if(paymentStatus){
            System.out.println("payment status TRUE");
            paymentStatusData.setPaymentStatus(false);
            clearTable();
            System.out.println("Payment status is True so the table will be cleared first");
        }
        else{
            System.out.println("Payment status is false, proceed as usual");
        }
        String inputcode = CodeTextField.getText();
        
        Item tempItem = null;
        
        int tempIndex = 0;
        for (Item item : itemlist) {
            
            if (item.getKode().equals(inputcode)) {
            
                tempIndex = JumlahBelanja;
                JumlahBelanja++;
                System.out.println("Item Found");
                
                transaksibarang.daftarIdBarang.add(Integer.valueOf(item.getKode()));
                transaksibarang.daftarJumlahBarang.add(JumlahBelanja);
                transaksibarang.daftarHargaBarang.add(item.getHarga());
                
                NameTextField.setText(item.getNama());
                PriceTextField.setText(Float.toString(item.getHarga()));
                
                daftarModel.setValueAt(JumlahBelanja, tempIndex, 0);
                daftarModel.setValueAt(inputcode, tempIndex, 1);
                daftarModel.setValueAt(item.getNama(), tempIndex, 2);
                daftarModel.setValueAt(item.getHarga(), tempIndex, 3);
                daftarModel.setValueAt(1, tempIndex, 4);
                
                
                tempItem = item;
                break;    
            }
        }
        if (tempItem == null) {
            System.out.println("Barang tidak ditemukan!");
            JOptionPane.showMessageDialog(null, "Item with code " + inputcode + " not found.");
        }
        CodeTextField.setText("");
        
    }//GEN-LAST:event_CodeTextFieldActionPerformed

    private void cashTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashTextFieldActionPerformed
        
//
//       String totalBelanjaString = totalBelanjaTextField.getText();
//       totalBelanjaString = totalBelanjaString.replace(",", "");
//       float totalBelanja = Float.parseFloat(totalBelanjaString);
//       
//       int transactionID = rand.nextInt(1000000);
//       id_transaksi = transactionID;
//       transaksibarang.id_transaksi = id_transaksi;
//       trans.id_transaksi = id_transaksi;
//       
//       trans.total_bayar = totalBelanja;
//       
//       String dibayarString = cashTextField.getText();
//       dibayarString = dibayarString.replace(",", "");
//       float dibayar = Float.parseFloat(dibayarString);
//       trans.total_bayar = dibayar;
//       
//       
//       if (dibayar < totalBelanja){
//           JOptionPane.showMessageDialog(null, "Jumlah Yang Anda Masukkan Tidak Cukup");
//           cashTextField.setText("");
//           balekTextfield.setText("");
//           return;
//       }
//       else{
//           trans.id_transaksi = id_transaksi;
//           trans.total_bayar = dibayar;
//       }
//       
//       int kembalian = (int) (dibayar - totalBelanja);
//       
//       trans.total_kembalian = kembalian;
//       balekTextfield.setText(String.format("%,d", kembalian));
//       
//       trans.insertDataTransaksi();
//       transaksibarang.insertDetailTransaksi();
          
    }//GEN-LAST:event_cashTextFieldActionPerformed
                                                    
    private void cashTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cashTextFieldKeyTyped

    private void cashTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashTextFieldKeyReleased
        // TODO add your handling code here:
        String dibayarString = cashTextField.getText();
        
        dibayarString = dibayarString.replace(",", "");
        
        try {
            float dibayarInput = Float.parseFloat(dibayarString);
            cashTextField.setText(String.format("%,.0f", dibayarInput));
        } 
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "INPUT HARUS BERUPA ANGKA!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cashTextFieldKeyReleased

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void PriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextFieldActionPerformed

    private void totalBelanjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBelanjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBelanjaTextFieldActionPerformed

    private void balekTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balekTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balekTextfieldActionPerformed

    private void ListrikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListrikButtonActionPerformed
        // TODO add your handling code here:
        TokenForm tokenform = new TokenForm();
        tokenform.setVisible(true);
    }//GEN-LAST:event_ListrikButtonActionPerformed

    private void PulsaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulsaButtonActionPerformed
        // TODO add your handling code here:
        PulsaForm pulsaform = new PulsaForm();
        pulsaform.setVisible(true);
    }//GEN-LAST:event_PulsaButtonActionPerformed

    private void BayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarButtonActionPerformed
        // TODO add your handling code here:
        BayarForm bayarForm = new BayarForm();
        bayarForm.getTotalBelanja(totalBelanjaTextField.getText());
        
        TransaksiBarang newTransaksiBarang = transaksibarang;
        transaksi newtransaksi = trans;
        
        bayarForm.setTransaksi(newtransaksi);
        bayarForm.setDetailTransaksi(newTransaksiBarang);
        bayarForm.setVisible(true);
    }//GEN-LAST:event_BayarButtonActionPerformed

    private void InputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputButtonActionPerformed
        // TODO add your handling code here:
        DataModel datamodel = new DataModel();
        DataThrown thrown = new DataThrown();
            
            String namaToken = "Token " + datamodel.getNominalToken();
            String namaPulsa = datamodel.getOperatorPulsa() + " " + datamodel.getNominalPulsa();

            Item tempBarang = null;

            int tempIndex = 0;

            for (Item item : itemlist) {
                if (item.getNama().equals(namaToken) || item.getNama().equals(namaPulsa)) {

                    tempIndex = JumlahBelanja;
                    JumlahBelanja++;

                    transaksibarang.daftarIdBarang.add(Integer.valueOf(item.getKode()));
                    transaksibarang.daftarJumlahBarang.add(JumlahBelanja);
                    transaksibarang.daftarHargaBarang.add(item.getHarga());

                    System.out.println("Barang ditemukan!");
                    
                    NameTextField.setText(item.getNama());
                    PriceTextField.setText(Float.toString(item.getHarga()));

                    daftarModel.setValueAt(JumlahBelanja, tempIndex, 0);
                    daftarModel.setValueAt(item.getKode(), tempIndex, 1);
                    daftarModel.setValueAt(item.getNama(), tempIndex, 2);
                    daftarModel.setValueAt(item.getHarga(), tempIndex, 3);
                    daftarModel.setValueAt(1, tempIndex, 4);
                    daftarModel.setValueAt(item.getHarga(), tempIndex, 5);
                    
                    break;
                }
                else{
                    System.out.println("Barang tidak ditemukan!");
                }
                
            }   
            if(namaPulsa!=null){
                datamodel.setNominalPulsa(null);
                datamodel.setOperatorPulsa(null);
                datamodel.setNomorTelepon(null);
            }
            else if(namaToken!= null){
                datamodel.setNominalToken(null);
                datamodel.setNomorMeteran(null);
            }
    }//GEN-LAST:event_InputButtonActionPerformed

    public void clearTable() {
        daftarModel = (DefaultTableModel) daftarTable.getModel();
            
            TableModelListener[] listeners = daftarModel.getTableModelListeners();
            
            
            for(TableModelListener listener : listeners){
                daftarModel.removeTableModelListener(listener);
            }
             
            int rowCount = daftarModel.getRowCount();
            int columnCount = daftarModel.getColumnCount();

            for(int i = 0;i<rowCount;i++){
                for(int j = 0;j<columnCount;j++){
                    daftarModel.setValueAt(null, i, j);
                }
            }
            
            JumlahBelanja = 0;
            transaksibarang.daftarHargaBarang.clear();
            transaksibarang.daftarIdBarang.clear();
            transaksibarang.daftarJumlahBarang.clear();
            
            System.out.println("Table Cleared");
            
            for(TableModelListener listener: listeners){
                daftarModel.addTableModelListener(listener);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarButton;
    private javax.swing.JTextField CodeTextField;
    private javax.swing.JButton InputButton;
    private javax.swing.JButton ListrikButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JButton PulsaButton;
    private javax.swing.JTextField balekTextfield;
    private javax.swing.JTextField cashTextField;
    private javax.swing.JTable daftarTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField totalBelanjaTextField;
    // End of variables declaration//GEN-END:variables

    
}
